[tool.poetry]
name = "scout"
version = "0.1.0"
description = ""
authors = ["Eivind Fonn <evfonn@gmail.com>"]

[tool.poetry.scripts]
scout = "scout.__main__:main"

[tool.poetry.dependencies]
python = "^3.8"
mayavi = "^4.7.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
